### docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - DATABASE_URL=postgresql://postgres:password@db:5432/digital_menu
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=digital_menu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:


